version: '3.3'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - WEB_CONCURRENCY=2
      - API_PRIVATE_ACCESS=true
    ports:
      - ${DOCKER_API_PORT:-8006}:80
