version: '3.3'

services:
  api_private:
    build:
      dockerfile: Dockerfile
      context: .
    restart: unless-stopped
    environment:
      - WEB_CONCURRENCY=2
      - API_PRIVATE_ACCESS=true
    ports:
      - ${DOCKER_API_PORT_PRIVATE:-8006}:80
