from enum import Enum


class EpigraphdbMetaNodesFull(str, Enum):
    """The version with special nodes included"""

    Disease = "Disease"
    Drug = "Drug"
    Efo = "Efo"
    Gene = "Gene"
    Gwas = "Gwas"
    Literature = "Literature"
    LiteratureTerm = "LiteratureTerm"
    LiteratureTriple = "LiteratureTriple"
    Pathway = "Pathway"
    Protein = "Protein"
    Tissue = "Tissue"
    Variant = "Variant"


class EpigraphdbMetaNodes(str, Enum):
    """The version without special nodes included"""

    Disease = "Disease"
    Drug = "Drug"
    Efo = "Efo"
    Gene = "Gene"
    Gwas = "Gwas"
    Literature = "Literature"
    LiteratureTerm = "LiteratureTerm"
    Pathway = "Pathway"
    Protein = "Protein"
    Tissue = "Tissue"
    Variant = "Variant"


class EpigraphdbMetaRels(str, Enum):
    BIORXIV_OBJ = "BIORXIV_OBJ"
    BIORXIV_PREDICATE = "BIORXIV_PREDICATE"
    BIORXIV_SUB = "BIORXIV_SUB"
    BIORXIV_TO_LIT = "BIORXIV_TO_LIT"
    CPIC = "CPIC"
    EFO_CHILD_OF = "EFO_CHILD_OF"
    EXPRESSED_IN = "EXPRESSED_IN"
    GENE_TO_PROTEIN = "GENE_TO_PROTEIN"
    GEN_COR = "GEN_COR"
    GWAS_EFO_EBI = "GWAS_EFO_EBI"
    GWAS_NLP = "GWAS_NLP"
    GWAS_NLP_EFO = "GWAS_NLP_EFO"
    GWAS_TO_LITERATURE = "GWAS_TO_LITERATURE"
    GWAS_TO_LITERATURE_TRIPLE = "GWAS_TO_LITERATURE_TRIPLE"
    GWAS_TO_VARIANT = "GWAS_TO_VARIANT"
    MEDRXIV_OBJ = "MEDRXIV_OBJ"
    MEDRXIV_PREDICATE = "MEDRXIV_PREDICATE"
    MEDRXIV_SUB = "MEDRXIV_SUB"
    MEDRXIV_TO_LIT = "MEDRXIV_TO_LIT"
    METAMAP_LITE = "METAMAP_LITE"
    MONDO_MAP_EFO = "MONDO_MAP_EFO"
    MONDO_MAP_UMLS = "MONDO_MAP_UMLS"
    MR_EVE_MR = "MR_EVE_MR"
    OBS_COR = "OBS_COR"
    OPENTARGETS_DRUG_TO_DISEASE = "OPENTARGETS_DRUG_TO_DISEASE"
    OPENTARGETS_DRUG_TO_TARGET = "OPENTARGETS_DRUG_TO_TARGET"
    PATHWAY_CHILD_OF = "PATHWAY_CHILD_OF"
    PROTEIN_IN_PATHWAY = "PROTEIN_IN_PATHWAY"
    PRS = "PRS"
    TERM_TO_GENE = "TERM_TO_GENE"
    SEMMEDDB_OBJ = "SEMMEDDB_OBJ"
    SEMMEDDB_PREDICATE = "SEMMEDDB_PREDICATE"
    SEMMEDDB_SUB = "SEMMEDDB_SUB"
    SEMMEDDB_TO_LIT = "SEMMEDDB_TO_LIT"
    STRING_INTERACT_WITH = "STRING_INTERACT_WITH"
    OPENGWAS_TOPHITS = "OPENGWAS_TOPHITS"
    VARIANT_TO_GENE = "VARIANT_TO_GENE"
    XQTL_MULTI_SNP_MR = "XQTL_MULTI_SNP_MR"
    XQTL_SINGLE_SNP_MR_GENE_GWAS = "XQTL_SINGLE_SNP_MR_GENE_GWAS"
    XQTL_SINGLE_SNP_MR_SNP_GENE = "XQTL_SINGLE_SNP_MR_SNP_GENE"
    GENE_TO_DISEASE = "GENE_TO_DISEASE"
